### PR TITLE
fix ListResource to adhere to fields and include query parameters

### PR DESCRIPTION
**Pull request by marcogrueter**

### CODE REVIEW

**Comment by samgreenwood** [comment]
Any idea when this will get merged?

**Comment by nilportugues** [comment]
@samgreenwood mind writing a test for it? I was going to do this myself, and I will before or during easter if not... but if you want this merged ASAP, provide a meaningful passing test.

I'm quite happy it didn't break anything, and I'm quite confident it won't break anything, but I still believe a test is required.

**Comment by marcogrueter** [comment]
Sorry, that should have been my thing.
Do you think it's ok if I copy the "testItWillSerializeToJsonApiAnArrayOfObjects" to "testItWillSerializeToJsonApiAnArrayOfObjectsAndFilterIncluded"?
I'm not that familiar with this repo.

**Comment by nilportugues** [comment]
@marcogrueter yes that will do.

**Pull request merged**
